language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "Build"
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - echo "Tag"
  - docker tag udagram-reverseproxy neikyl/udagram-reverseproxy:v1
  - docker tag udagram-api-feed neikyl/udagram-api-feed:v1
  - docker tag udagram-api-user neikyl/udagram-api-user:v1
  - docker tag udagram-frontend neikyl/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - echo "Start pushing"
  - docker push neikyl/udagram-reverseproxy:v1
  - docker push neikyl/udagram-api-feed:v1
  - docker push neikyl/udagram-api-user:v1
  - docker push neikyl/udagram-frontend:v1